-- 1
SELECT ROUND(avg(daily_fee)) as 'AVERAGE_FEE'
from CAR_RENTAL_COMPANY_CAR
where car_type = 'SUV';

-- 2 
SELECT DR_NAME, DR_ID, MCDP_CD, DATE_FORMAT(HIRE_YMD, '%Y-%m-%d')
FROM DOCTOR
WHERE MCDP_CD IN('CS', 'GS')
ORDER BY HIRE_YMD DESC, DR_NAME;

-- 3
SELECT I.FLAVOR
FROM ICECREAM_INFO I, FIRST_HALF F
WHERE I.FLAVOR = F.FLAVOR and F.TOTAL_ORDER > 3000
    and I.INGREDIENT_TYPE = 'fruit_based'
ORDER BY total_order desc;

-- 4
SELECT MEMBER_ID, MEMBER_NAME, GENDER, 
    DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') as 'DATE_OF_BIRTH'
FROM MEMBER_PROFILE 
WHERE Month(DATE_OF_BIRTH) = 3 and TLNO is not null and GENDER = 'W'
ORDER BY MEMBER_ID;

-- 5
SELECT RR.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, 
    ROUND(avg(RR.REVIEW_SCORE),2) as 'SCORE'
FROM REST_INFO RI, REST_REVIEW RR
WHERE RI.REST_ID = RR.REST_ID
GROUP BY RI.REST_ID
HAVING RI.ADDRESS like '서울%'
ORDER BY SCORE DESC, RI.FAVORITES DESC;

-- 6
SELECT UB.TITLE, UB.BOARD_ID, UR.REPLY_ID, UR.WRITER_ID, UR.CONTENTS, 
    DATE_FORMAT(UR.CREATED_DATE, '%Y-%m-%d') as 'CREATED_DATE'
FROM USED_GOODS_BOARD UB, USED_GOODS_REPLY UR
WHERE UB.BOARD_ID = UR.BOARD_ID and
    YEAR(UB.CREATED_DATE) = 2022 and 
    Month(UB.CREATED_DATE) = 10
ORDER BY UR.CREATED_DATE, UB.TITLE;

-- 7
SELECT FLAVOR
FROM FIRST_HALF 
ORDER BY TOTAL_ORDER DESC, SHIPMENT_ID;

-- 8
SELECT FACTORY_ID, FACTORY_NAME, ADDRESS
FROM FOOD_FACTORY 
WHERE ADDRESS LIKE '강원도%'
ORDER BY FACTORY_ID;

-- 9
SELECT PT_NAME, PT_NO, GEND_CD, AGE, ifnull(TLNO, 'NONE')
FROM PATIENT 
WHERE AGE <= 12 and GEND_CD = 'W'
ORDER BY AGE DESC, PT_NAME;

-- 10
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') as 'PUBLISHED_DATE'
FROM BOOK
WHERE Year(PUBLISHED_DATE) = 2021 and CATEGORY = '인문'
ORDER BY PUBLISHED_DATE;

-- 11
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE 
GROUP BY USER_ID, PRODUCT_ID
HAVING count(*) > 1
ORDER BY USER_ID, PRODUCT_ID desc;

-- 12
SELECT *
FROM ANIMAL_INS 
ORDER BY ANIMAL_ID;

-- 13
SELECT NAME, DATETIME
FROM ANIMAL_INS 
ORDER BY ANIMAL_ID DESC;

-- 14


