-- 1
SELECT MAX(price) as MAX_PRICE
FROM PRODUCT ;

-- 2 가격이 제일 비싼 식품의 정보 출력하기
SELECT *
FROM FOOD_PRODUCT
WHERE PRICE = (select max(price) from food_product);

-- 3 
SELECT DATETIME as '시간'
FROM ANIMAL_INS 
ORDER BY DATETIME DESC
LIMIT 1;

-- 4
SELECT DATETIME as '시간'
FROM ANIMAL_INS 
ORDER BY DATETIME 
LIMIT 1;

-- 5
SELECT count(*) as count
FROM ANIMAL_INS; 

-- 6
SELECT count(distinct NAME) as count
FROM ANIMAL_INS ;

-- 7 
SELECT SUM(PRICE) as TOTAL_PRICE
FROM ITEM_INFO 
WHERE RARITY = 'LEGEND';

-- 8 
SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO FI JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FI.LENGTH = (SELECT MAX(LENGTH)
                    FROM FISH_INFO FI2
                    WHERE FI.FISH_TYPE = FI2.FISH_TYPE
                    GROUP BY FNI.FISH_TYPE)
ORDER BY ID;

-- 9 
SELECT concat(max(LENGTH),'cm') as 'MAX_LENGTH'
FROM FISH_INFO ;